"""Place three toy systems on the (closure, memory) autonomy plane.

Run from the repository root::

    python examples/automaton_demo.py

All three systems observe the same environment trace.

- System A (self-ruled) derives every transition from its own previous
  state. High closure, trivially periodic: high on the closure axis,
  but memory is capped at ``log2(n_states)``.
- System B (environment-driven) derives every transition from the
  environment input plus a small amount of noise. Low closure, low
  memory.
- System C (mixed) is the same self-ruled table as A wrapped in a
  decision that falls back to the environment with a small
  probability. It sits between A and B.

Running the demo prints an ``AutonomyProfile`` for each system plus a
one-line reading of where they land on the plane.
"""

from __future__ import annotations

import numpy as np

from autonometrics import (
    Autonometer,
    AutonomyProfile,
    SimpleAutomaton,
    __version__,
)


class _MixedAutomaton:
    """Toy system blending a self-rule with an environment-driven fallback.

    The history is generated by following ``SimpleAutomaton``'s
    self-rule with probability ``1 - env_weight`` and by copying the
    current environment symbol modulo ``n_states`` with probability
    ``env_weight``. It exposes the same ``get_state_history`` /
    ``get_env_history`` protocol as ``SimpleAutomaton``.
    """

    def __init__(
        self,
        n_states: int,
        env: np.ndarray,
        seed: int,
        env_weight: float = 0.3,
    ) -> None:
        self._base = SimpleAutomaton.from_self_generated_rules(
            n_states=n_states, env=env, seed=seed
        )
        base_history = self._base.get_state_history()
        rng = np.random.default_rng(seed + 1)
        mask = rng.random(size=base_history.size) < env_weight
        mixed = np.where(mask, env % n_states, base_history).astype(np.int64)
        self._states = mixed
        self._env = env.copy()

    def get_state_history(self) -> np.ndarray:
        return self._states.copy()

    def get_env_history(self) -> np.ndarray:
        return self._env.copy()


def _format_score(value: float | None) -> str:
    return "  n/a" if value is None else f"{value:5.2f}"


def _plane_reading(profile: AutonomyProfile) -> str:
    closure = profile.ratio_endo_total or 0.0
    memory = profile.structural_memory or 0.0
    closure_label = "high closure" if closure >= 0.5 else "low closure"
    memory_label = "high memory" if memory >= 1.0 else "low memory"
    if closure >= 0.5 and memory >= 1.0:
        zone = "candidate autopoietic corner"
    elif closure >= 0.5:
        zone = "clockwork"
    elif memory >= 1.0:
        zone = "turbulence"
    else:
        zone = "drift"
    return f"{closure_label}, {memory_label}  ->  {zone}"


def main() -> None:
    n_states = 4
    n_env_symbols = 3
    n_steps = 3000
    seed = 0

    rng = np.random.default_rng(seed)
    env = rng.integers(0, n_env_symbols, size=n_steps).astype(np.int64)

    system_a = SimpleAutomaton.from_self_generated_rules(n_states=n_states, env=env, seed=seed)
    system_b = SimpleAutomaton.from_external_rules(n_states=n_states, env=env, seed=seed)
    system_c = _MixedAutomaton(n_states=n_states, env=env, seed=seed, env_weight=0.3)

    meter = Autonometer(metrics=["albantakis", "memory"])
    profile_a = meter.measure(system_a)
    profile_b = meter.measure(system_b)
    profile_c = meter.measure(system_c)

    print(f"Autonometrics v{__version__}  autonomy-plane demo")
    print()
    print(f"{'system':<32}{'closure':>10}{'memory':>10}   plane reading")
    print("-" * 80)
    for name, profile in (
        ("A: self-ruled", profile_a),
        ("B: env-driven + noise", profile_b),
        ("C: mixed 70/30", profile_c),
    ):
        print(
            f"{name:<32}"
            f"{_format_score(profile.ratio_endo_total):>10}"
            f"{_format_score(profile.structural_memory):>10}"
            f"   {_plane_reading(profile)}"
        )


if __name__ == "__main__":
    main()
