"""Place three toy systems on the canonical [0, 1] x [0, 1] autonomy plane.

Run from the repository root::

    python examples/automaton_demo.py

All three systems observe the same environment trace and are scored on
two PBA-coherent ratios:

- ``closure`` (Albantakis): how much of the next state is determined
  by the system's own past, controlling for the environment.
- ``memory`` (memory_endo_ratio): of the structural memory in the
  joint (system, environment) trajectory, how much is carried by the
  system itself.

Both axes live in ``[0, 1]`` and the four quadrants are split by the
0.5 threshold on each axis:

- System A (self-ruled): high closure, memory dominated by the
  system itself (the environment is i.i.d. noise).
- System B (environment-driven): low closure; the system's
  contribution to joint memory drops as well.
- System C (mixed): a self-rule with a stochastic environment
  fallback; sits between A and B.

The script prints an ``AutonomyProfile`` for each system plus a
one-line reading of where it lands on the plane.
"""

from __future__ import annotations

import numpy as np

from autonometrics import (
    Autonometer,
    AutonomyProfile,
    SimpleAutomaton,
    __version__,
)


class _MixedAutomaton:
    """Toy system blending a self-rule with an environment-driven fallback.

    The history is generated by following ``SimpleAutomaton``'s
    self-rule with probability ``1 - env_weight`` and by copying the
    current environment symbol modulo ``n_states`` with probability
    ``env_weight``. It exposes the same ``get_state_history`` /
    ``get_env_history`` protocol as ``SimpleAutomaton``.
    """

    def __init__(
        self,
        n_states: int,
        env: np.ndarray,
        seed: int,
        env_weight: float = 0.3,
    ) -> None:
        self._base = SimpleAutomaton.from_self_generated_rules(
            n_states=n_states, env=env, seed=seed
        )
        base_history = self._base.get_state_history()
        rng = np.random.default_rng(seed + 1)
        mask = rng.random(size=base_history.size) < env_weight
        mixed = np.where(mask, env % n_states, base_history).astype(np.int64)
        self._states = mixed
        self._env = env.copy()

    def get_state_history(self) -> np.ndarray:
        return self._states.copy()

    def get_env_history(self) -> np.ndarray:
        return self._env.copy()


def _format_score(value: float | None) -> str:
    return "  n/a" if value is None else f"{value:5.2f}"


def _plane_reading(profile: AutonomyProfile) -> str:
    closure = profile.ratio_endo_total or 0.0
    memory = profile.memory_endo_ratio or 0.0
    closure_label = "high closure" if closure >= 0.5 else "low closure"
    memory_label = "high memory" if memory >= 0.5 else "low memory"
    if closure >= 0.5 and memory >= 0.5:
        zone = "candidate autopoietic corner"
    elif closure >= 0.5:
        zone = "clockwork"
    elif memory >= 0.5:
        zone = "turbulence"
    else:
        zone = "drift"
    return f"{closure_label}, {memory_label}  ->  {zone}"


def main() -> None:
    n_states = 4
    n_env_symbols = 3
    n_steps = 3000
    seed = 0

    rng = np.random.default_rng(seed)
    env = rng.integers(0, n_env_symbols, size=n_steps).astype(np.int64)

    system_a = SimpleAutomaton.from_self_generated_rules(n_states=n_states, env=env, seed=seed)
    system_b = SimpleAutomaton.from_external_rules(n_states=n_states, env=env, seed=seed)
    system_c = _MixedAutomaton(n_states=n_states, env=env, seed=seed, env_weight=0.3)

    meter = Autonometer(metrics=["albantakis", "memory"])
    profile_a = meter.measure(system_a)
    profile_b = meter.measure(system_b)
    profile_c = meter.measure(system_c)

    print(f"Autonometrics v{__version__}  PBA-coherent autonomy plane demo")
    print()
    print(f"{'system':<32}{'closure':>10}{'memory':>10}   plane reading")
    print("-" * 80)
    for name, profile in (
        ("A: self-ruled", profile_a),
        ("B: env-driven + noise", profile_b),
        ("C: mixed 70/30", profile_c),
    ):
        print(
            f"{name:<32}"
            f"{_format_score(profile.ratio_endo_total):>10}"
            f"{_format_score(profile.memory_endo_ratio):>10}"
            f"   {_plane_reading(profile)}"
        )


if __name__ == "__main__":
    main()
